name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  CD:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
        
    - name: Build The Application
      run: mvn -B -f pom.xml clean install -Dmaven.test.skip=true
    
    - name: Deploy Docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker build . -t kevinalef/java-api
        docker push kevinalef/java-api
